/**
 * `agentstoz_use` MCP 서버를 **앱 교체에서 떼어 내는** 런처.
 *
 * 지금까지 네 AI 설정에 적히는 명령은 앱 번들 안의 실행 파일이었다
 * (`/Applications/AgentsToZ_byCS.app/Contents/Resources/resources/agentstoz-use-mcp`).
 * 그런데 앱 업데이트는 그 번들을 **통째로 지웠다 복사한다** — DMG를 끌어다 놓는 보통의 설치도 같다.
 * 그 창(수 초~수십 초) 안에 시작한 CLI 세션은 서버를 **아예 띄우지 못하고**, 그 세션은 끝날 때까지
 * `agentstoz_use` 도구가 하나도 없는 채로 돈다. 실측(2026-10-06): Codex 세션이 13:33에 「해당 도구를
 * 사용할 수 없다」고 보고했고, 그때 설치된 앱 바이너리의 mtime 이 13:34였다.
 *
 * 그래서 설정에는 **홈 아래 고정 경로**를 적고, 그 런처가 실행 시점에 진짜 바이너리를 찾는다.
 * 교체 중이면 잠깐 기다렸다가 간다 — 기다리는 쪽이 「도구 없음」보다 언제나 낫다.
 *
 * ⚠️ 런처는 **앱을 대신 실행할 뿐 권한을 늘리지 않는다.** 찾는 경로는 ① `AGENTSTOZ_USE_MCP_PATH`
 * ② 앱이 적어 둔 번들 경로 ③ (있다면) 개발 소스뿐이고, 인자와 stdio 는 그대로 넘긴다.
 */

/** 설정 파일에 적히는 고정 경로. 앱이 사라져도 이 경로는 남는다. */
export function agentsToZUseMcpLauncherPath(home: string, platform: string = process.platform): string {
  const name = platform === 'win32' ? 'agentstoz-use-mcp.cmd' : 'agentstoz-use-mcp';
  return `${home}/.agentstoz/bin/${name}`;
}

/** 앱 교체를 기다리는 시간. 0.5초 × 40 = 20초 — DMG 복사가 끝나기에 충분하고, 영원히 매달리지 않는다. */
export const AGENTSTOZ_USE_MCP_LAUNCHER_WAIT_STEPS = 40;

const shellQuote = (value: string) => `'${value.replaceAll("'", `'\\''`)}'`;

/**
 * 런처 본문. 생성물이므로 손으로 고치지 말 것 — 앱이 연결을 준비할 때마다 덮어쓴다.
 * `bundled` 는 지금 설치된 앱의 실행 파일, `dev` 는 소스에서 돌릴 때의 대체 경로다.
 */
export function agentsToZUseMcpLauncherScript(input: {bundled: string; dev?: string | null}): string {
  const bundled = shellQuote(input.bundled);
  const dev = input.dev ? shellQuote(input.dev) : "''";
  return `#!/bin/sh
# Generated by AgentsToZ — do not edit. The app rewrites this file when it prepares AI connections.
#
# 설정 파일이 앱 번들 안을 직접 가리키면, 앱을 교체하는 동안 시작한 CLI 세션은 MCP 서버를 띄우지
# 못하고 그 세션 내내 agentstoz_use 도구가 없다. 이 런처가 실행 시점에 바이너리를 찾고, 교체 중이면
# 잠깐 기다린다.
set -eu
# WARNING: a quoted default inside a parameter expansion becomes literal text (measured), so the
# fallback is assigned separately. Do not fold it back into one line.
BIN=\${AGENTSTOZ_USE_MCP_PATH:-}
if [ -z "$BIN" ]; then BIN=${bundled}; fi
DEV=${dev}
i=0
while [ ! -x "$BIN" ] && [ "$i" -lt ${AGENTSTOZ_USE_MCP_LAUNCHER_WAIT_STEPS} ]; do
  sleep 0.5
  i=$((i+1))
done
if [ ! -x "$BIN" ] && [ -n "$DEV" ] && [ -x "$DEV" ]; then
  BIN="$DEV"
fi
exec "$BIN" "$@"
`;
}

/**
 * 설정에 **적어야 할** 명령. 런처가 이미 있으면 런처, 아직 없으면 번들 경로다.
 *
 * ⚠️ 두 설치기(OPS 프로필 연결·Buzz 부트스트랩)가 **같은 답**을 써야 한다 — 한쪽이 런처를 적고 다른
 * 쪽이 번들을 기대하면, 상대가 쓴 항목을 「충돌」로 판정해 사용자에게 고치라고 한다(이 저장소가 이미
 * 한 번 겪은 함정이다). 그래서 판정을 이 함수 하나로 모은다.
 */
export function agentsToZUseMcpConfiguredCommand(
  home: string,
  bundled: string | null,
  exists: (path: string) => boolean,
  platform: string = process.platform,
): string | null {
  if (!bundled) return null;
  if (platform === 'win32') return bundled;
  const launcher = agentsToZUseMcpLauncherPath(home, platform);
  return exists(launcher) ? launcher : bundled;
}

/**
 * 이 명령이 **우리가 적은 것**인가. 런처는 물론이고, 예전에 적었던 번들 경로도 우리 것이다 —
 * 그래야 「사용자가 직접 만든 다른 연결」과 구분해서 조용히 올려 줄 수 있다.
 */
export function isAgentsToZUseMcpCommand(command: unknown, launcher: string, bundled?: string | null): boolean {
  if (typeof command !== 'string' || !command) return false;
  if (command === launcher) return true;
  if (bundled && command === bundled) return true;
  // 앱 번들 안의 같은 이름이면 우리 것이다(설치 위치·버전이 달라도). 개발 소스 경로도 같다.
  return /(?:^|\/)agentstoz-use-mcp(?:\.cmd|\.exe)?$/.test(command)
    && (command.includes('/AgentsToZ') || command.includes('/.agentstoz/bin/') || command.includes('src-tauri/resources/'));
}

/** 우리 것이지만 **옛 모양**이면 런처로 올린다. 이미 런처면 그대로 둔다. */
export function agentsToZUseMcpCommandNeedsUpgrade(command: unknown, launcher: string, bundled?: string | null): boolean {
  return isAgentsToZUseMcpCommand(command, launcher, bundled) && command !== launcher;
}
